### PR TITLE
Added tests, updated readme, and added ability to successfully test an expired cert

### PR DESCRIPTION
**Pull request by pgporada**
## Pull Request Checklist

**Is this in reference to an existing issue?**
No it is not

#### General

- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [X] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass 

#### New Plugins
Technically this is an upgrade to a plugin that didn't have tests. There are now tests.

- [X] Tests

- [X] Add the plugin to the README

- [X] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

I need to check that a certificate is correctly and successfully expired. Basically the opposite of what the standard check-https-cert.rb is used for.

### CODE REVIEW

**Comment by eheydrick** [comment]
Thanks for the additions @pgporada. Can you add an entry to the CHANGELOG.md under Unreleased and we'll get this merged.

**Comment by pgporada** [comment]
Updates to the CHANGELOG.md have been made. 👍

**Comment by eheydrick** [comment]
Thanks again @pgporada! I'll cut a new release shortly.

**Comment by eheydrick** [comment]
Released in 2.4.0, now live on rubygems.

**Pull request merged**
