### PR TITLE
fixing issue with regexp

### PR DESCRIPTION
**Pull request by nevins-b**
## Pull Request Checklist

**Is this in reference to an existing issue?**
#58 and #48 
#### General

- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by eheydrick** [comment]
Thanks for this PR. Can you resolve the rubocop issue and we'll get this merged. https://travis-ci.org/sensu-plugins/sensu-plugins-http/jobs/207446029

**Comment by ushi-as** [comment]
@eheydrick any news on this. metrics-http-json-deep.rb is unusable at the moment.

**Comment by eheydrick** [comment]
Thanks for the fix. Will cut a new release soon.

**Comment by eheydrick** [comment]
The fix is in 2.0.2.

**Pull request merged**
