### PR TITLE
Updates the timeout call to fix deprecation warning.

### LINKED ISSUE #35: Object#timeout is deprecated, use Timeout.timeout instead.
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-http-0.2.1/bin/check-http.rb:183:in `run': Object#timeout is deprecated, use Timeout.timeout instead.
```

### PR DESCRIPTION
**Pull request by mlehner616**
This should resolve #35 for new version of sensu. Feedback welcome, first PR to sensu* project. Thanks

### CODE REVIEW

**Comment by sstarcher** [comment]
Ci is failing

**Comment by mlehner616** [comment]
Ci is already failing on master

**Comment by sstarcher** [comment]
Good point

**Comment by eheydrick** [comment]
CI is fixed, btw.

**Comment by calebhailey** [comment]
:+1: nice quick fix!

**Pull request merged**
