### PR TITLE
Add ability to print whole response in check-http

### PR DESCRIPTION
**Pull request by kmejka**
This PR is a proposition of two changes:
- Add the -w or --whole-response to the check-http.rb check. When the check is failing, the whole message received will be displayed in the message
- Add the intellij project files to ignored in gitignore.

This is the PR requested by @mattyjones in this PR on the (soon deprecated) [sensu-community-plugins](https://github.com/sensu/sensu-community-plugins): https://github.com/sensu/sensu-community-plugins/pull/1195

### CODE REVIEW

**Comment by mattyjones** [comment]
@kmejka Can you take a look at the Travis output please

Thanks!

**Comment by kmejka** [comment]
@mattyjones I made a dumb mistake, placing the comma in the wrong line. Anyway, I've udpated the code fixing the bug, and now the build seems to be succeeding.

**Comment by mattyjones** [comment]
@kmejka  Can you update the CHANGELOG please and I will merge this.

Thanks!

**Comment by kmejka** [comment]
@mattyjones I've updated the changelog, please tell me if it's ok.
- Since this is a new feature I'm adding (albeit a small one), I've defined the version as 0.1.0. Version 0.0.3 would be fine as well, what do you think?
- I've added to the changelog the tag 0.0.2 from 2015-06-03, but I didn't know what to write in the description, since it was just a change to make the project build (I think?). Is that okay?

**Comment by mattyjones** [comment]
@kmejka  Sorry for the long response time.  Yes you are fine.  I will make note that in the future when adding new scripts the minor number will be bumped and not the patch number.

We are still fleshing out a lot of things with the new org and seeing how things progress as we go.

**Comment by kmejka** [comment]
@mattyjones hey man no problem with the response time don't worry about it :).
Thanks for merging, have a nice day.

**Pull request merged**
