### PR TITLE
check-https-cert update internal documentation/wording

### PR DESCRIPTION
**Pull request by pgporada**
## Pull Request Checklist

There was no prior ticket for this.

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Updates the internal checks documentation and provides example usage.

#### Known Compatablity Issues

None

### CODE REVIEW

**Comment by majormoses** [comment]
@pgporada fyi this might be something you want to consider incorporating here: https://github.com/sensu-plugins/sensu-plugins-http/pull/71

**Comment by pgporada** [comment]
Ah, I see what you mean. I will try to come up with something.

**Comment by pgporada** [comment]
I added the check name I altered to your note.

**Comment by majormoses** [comment]
@pgporada thanks I saw there were merge conflicts so I rebased on your behalf and will squash merge after CI passes.

**Comment by majormoses** [comment]
please ping me if I do not release in the next 24 hours.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-http/versions/2.1.0

**Comment by pgporada** [comment]
\o @mattyjones

**Pull request merged**
