### PR TITLE
use rest-client 2.0 to fix issue with OpenSSL 1.1.0

### LINKED ISSUE #81: Rest-Client 1.8 is incompatible with OpenSSL 1.1.0
Rest-Client 1.8 is incompatible with OpenSSL 1.1.0. See:

- https://github.com/rest-client/rest-client/pull/573
- https://github.com/rest-client/rest-client/issues/569

This makes metrics-http-json.rb unusable on machines with OpenSSL 1.1.0. Please update the rest-client dependency to 2.0.2

### PR DESCRIPTION
**Pull request by ushis**
## Pull Request Checklist

Fixes #81

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

fix

#### Known Compatibility Issues

none

### CODE REVIEW

**Comment by majormoses** [comment]
@ushis looks like that introduces a breaking change that forces us to drop ruby 2.1 which is still a supported version of ruby so we need to figure out of we can lock this dependency: https://travis-ci.org/sensu-plugins/sensu-plugins-http/jobs/258855032#L561 to keep ruby 2.1 support for this to be accepted. Our official stance is regarding ruby version support: https://github.com/sensu-plugins/documentation/blob/master/docs/FAQ.md#what-is-the-policy-on-supporting-end-of-lifeeol-ruby-versions.

**Comment by ushi-as** [comment]
@majormoses According to the travis log, this is a problem introduced by kitchen-localhost, not by rest-client.

```
Gem::InstallError: mixlib-shellout requires Ruby version >= 2.2.
An error occurred while installing mixlib-shellout (2.3.2), and
Bundler cannot continue.
Make sure that `gem install mixlib-shellout -v '2.3.2'` succeeds before
bundling.

In Gemfile:
  kitchen-localhost was resolved to 0.3.0, which depends on
    test-kitchen was resolved to 1.16.0, which depends on
      mixlib-install was resolved to 2.1.12, which depends on
        mixlib-shellout
```

**Comment by majormoses** [comment]
@ushi-as ok, can you lock down that down to make it work with ruby 2.1?

**Comment by ushis** [comment]
@majormoses done

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-http/versions/2.6.0

**Pull request merged**
