### PR TITLE
Update check-http-json.rb, add POST and post body

### PR DESCRIPTION
**Pull request by FlorinAndrei**
Added an option to use POST instead of GET.

Added option to slurp a POST body from a file.

### CODE REVIEW

**Comment by mattyjones** [comment]
@FlorinAndrei  Can you update the CHANGELOG please

Thanks!

**Comment by FlorinAndrei** [comment]
done

**Comment by mattyjones** [comment]
@FlorinAndrei  I don't see the updated changelog...am I blind ;)

**Comment by FlorinAndrei** [comment]
https://github.com/sensu-plugins/sensu-plugins-http/pull/12

**Pull request merged**
